### ISSUE TITLE
connection timeout when creating connection

### ISSUE THREAD

**Issue by justinsaraceno** [cmendible/dotnetcore.samples#1]
Thanks for this sample code!  I've created an Azure Service Bus namespace, topic, and have credentials.  When attempting to create the connection `var connection = new Connection(address);`, it times out with the following stack trace from AMQPNetLite:
```
{System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Amqp.TcpTransport.<ConnectAsync>d__8.MoveNext() in d:\Source\Repos\amqpnetlite-git\src\Net\TcpTransport.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
```
In the Azure Service Bus manager monitoring view, I can see the topic is receiving successful requests so I know I'm hitting the correct endpoint.  I've tried both the Sync and Async APIs [http://azure.github.io/amqpnetlite/articles/building_application.html] with the same result.  Did you ever get this too?  Is there some other step on Azure Service Bus config side or your dev environment that you may have done?  Thanks

**Comment by justinsaraceno** [comment]
I've tracked down this issue.  Apparently there's been some changes on the AMQPNetLite side since your example.  It looks like websocket support was evolving both on the dotnet core side and in AMQPNetLite.  The issue is detailed here: [https://github.com/Azure/amqpnetlite/issues/138](url)

The fix was to install the AMQPNetLite.WebSockets NuGet package, define the Address to use websockets:

`var address = new Address(configuration["ServiceBus:NamespaceUrl"], 443, configuration["ServiceBus:PolicyName"], configuration["ServiceBus:Key"], "/$servicebus/websocket", "WSS");`

and then use the ConnectionFactory to define a Web Socket transport provider:

```
ConnectionFactory connectionFactory = new ConnectionFactory(new TransportProvider[] {new WebSocketTransportFactory()});
var connection = connectionFactory.CreateAsync(address).Result;
```

**Comment by cmendible** [comment]
Somehow I missed the notifications on this issue. 
I never faced such a problem before. In fact I just tried the sample and it still works without any changes.
Let me know if you made any changes that would cause the issue.
Glad to hear that you found the code helpful.
