### ISSUE TITLE
illustration 

### ISSUE THREAD

**Issue by ClientIco** [cmendible/dotnetcore.samples#2]
https://github.com/cmendible/dotnetcore.samples/blob/master/roslyn.create.class/Program.cs

I am missing this function : 

        public static Type CreateClass(params DynamicProperty[] properties);
        public static Type CreateClass(IEnumerable<DynamicProperty> properties);

From what I can see your example would allow me in .net Core to create a class, What I need is to create a class from off a Dictionary with Dynamic keys properties :

var fieldProps = new Dictionary<System.Linq.Dynamic.Core.DynamicProperty, object>();
fieldProps.Add(new System.Linq.Dynamic.Core.DynamicProperty(aggregate.Aggregate, typeof(object)), val);

 type = System.Linq.Expressions.DynamicExpression.**CreateClass**(fieldProps.Keys);
                    var fieldObj = Activator.CreateInstance(type);
                    foreach (var p in fieldProps.Keys)
                        type.GetProperty(p.Name).SetValue(fieldObj, fieldProps[p], null);
                    objProps.Add(new System.Linq.Dynamic.Core.DynamicProperty(group.Key, fieldObj.GetType()), fieldObj);

Maybe there is a easier why to do what I want to do rather than using  DynamicExpression

Would you be able to put down such an example ?

**Comment by cmendible** [comment]
When you use the System.Linq.Expressions.DynamicExpression.CreateClass method you are creating Data classes which lives in an in-memory assembly in the current application domain. I'm not sure if you want to generate the c# code for the class, as I do in the provided code, or if you want to dynamically create and uses classes at runtime (out of the scope of the original code).

If you want to generate code, you just have to modify the signature of the [CreateClass] (https://github.com/cmendible/dotnetcore.samples/blob/master/roslyn.create.class/Program.cs) method to receive some parameters such as: Namespace, class name, IEnumerable< [Custom field descriptor type]>, etc… and then modify the body to use them and loop as necessary.

Hope it helps!
