### ISSUE TITLE
Needs an update to new ML framework

### ISSUE THREAD

**Issue by mattdunndc** [cmendible/dotnetcore.samples#3]
LearningPipeline is obsolete

**Comment by cmendible** [comment]
Hi @mattdunndc you can check the updated sample [here](https://github.com/cmendible/dotnetcore.samples/tree/master/titanic.ml).

**Comment by mattdunndc** [comment]
> Hi @mattdunndc you can check the updated sample [here](https://github.com/cmendible/dotnetcore.samples/tree/master/titanic.ml).

Awesome!  I will try it tonight.  Really appreciate the effort.   Best,
